// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.access_key_permission_kind */
type AccessKeyPermissionKind = "FULL_ACCESS" | "FUNCTION_CALL";

export default AccessKeyPermissionKind;
