// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type AccessKeyPermissionKind from "./access-key-permission-kind";
import type { ReceiptsReceiptId } from "./receipts";

/** Identifier type for public.access_keys */
export type AccessKeysPublicKey = string & { __flavor?: "AccessKeysPublicKey" };

/** Identifier type for public.access_keys */
export type AccessKeysAccountId = string & { __flavor?: "AccessKeysAccountId" };

/** Represents the table public.access_keys */
export default interface AccessKeys {
  public_key: AccessKeysPublicKey;

  account_id: AccessKeysAccountId;

  created_by_receipt_id: ReceiptsReceiptId | null;

  deleted_by_receipt_id: ReceiptsReceiptId | null;

  permission_kind: AccessKeyPermissionKind;

  last_update_block_height: string;
}

/** Represents the initializer for the table public.access_keys */
export interface AccessKeysInitializer {
  public_key: AccessKeysPublicKey;

  account_id: AccessKeysAccountId;

  created_by_receipt_id?: ReceiptsReceiptId | null;

  deleted_by_receipt_id?: ReceiptsReceiptId | null;

  permission_kind: AccessKeyPermissionKind;

  last_update_block_height: string;
}

/** Represents the mutator for the table public.access_keys */
export interface AccessKeysMutator {
  public_key?: AccessKeysPublicKey;

  account_id?: AccessKeysAccountId;

  created_by_receipt_id?: ReceiptsReceiptId | null;

  deleted_by_receipt_id?: ReceiptsReceiptId | null;

  permission_kind?: AccessKeyPermissionKind;

  last_update_block_height?: string;
}
