// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ReceiptsReceiptId } from "./receipts";

/** Identifier type for public.accounts */
export type AccountsId = string & { __flavor?: "AccountsId" };

/** Represents the table public.accounts */
export default interface Accounts {
  id: AccountsId;

  account_id: string;

  created_by_receipt_id: ReceiptsReceiptId | null;

  deleted_by_receipt_id: ReceiptsReceiptId | null;

  last_update_block_height: string;
}

/** Represents the initializer for the table public.accounts */
export interface AccountsInitializer {
  /** Default value: nextval('accounts_id_seq'::regclass) */
  id?: AccountsId;

  account_id: string;

  created_by_receipt_id?: ReceiptsReceiptId | null;

  deleted_by_receipt_id?: ReceiptsReceiptId | null;

  last_update_block_height: string;
}

/** Represents the mutator for the table public.accounts */
export interface AccountsMutator {
  id?: AccountsId;

  account_id?: string;

  created_by_receipt_id?: ReceiptsReceiptId | null;

  deleted_by_receipt_id?: ReceiptsReceiptId | null;

  last_update_block_height?: string;
}
