// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { BlocksBlockHash } from "./blocks";
import type { ReceiptsReceiptId } from "./receipts";
import type StateChangeReasonKind from "./state-change-reason-kind";
import type { TransactionsTransactionHash } from "./transactions";

/** Identifier type for public.account_changes */
export type AccountChangesId = string & { __flavor?: "AccountChangesId" };

/** Represents the table public.account_changes */
export default interface AccountChanges {
  id: AccountChangesId;

  affected_account_id: string;

  changed_in_block_timestamp: string;

  changed_in_block_hash: BlocksBlockHash;

  caused_by_transaction_hash: TransactionsTransactionHash | null;

  caused_by_receipt_id: ReceiptsReceiptId | null;

  update_reason: StateChangeReasonKind;

  affected_account_nonstaked_balance: string;

  affected_account_staked_balance: string;

  affected_account_storage_usage: string;

  index_in_block: number;
}

/** Represents the initializer for the table public.account_changes */
export interface AccountChangesInitializer {
  /** Default value: nextval('account_changes_new_id_seq'::regclass) */
  id?: AccountChangesId;

  affected_account_id: string;

  changed_in_block_timestamp: string;

  changed_in_block_hash: BlocksBlockHash;

  caused_by_transaction_hash?: TransactionsTransactionHash | null;

  caused_by_receipt_id?: ReceiptsReceiptId | null;

  update_reason: StateChangeReasonKind;

  affected_account_nonstaked_balance: string;

  affected_account_staked_balance: string;

  affected_account_storage_usage: string;

  index_in_block: number;
}

/** Represents the mutator for the table public.account_changes */
export interface AccountChangesMutator {
  id?: AccountChangesId;

  affected_account_id?: string;

  changed_in_block_timestamp?: string;

  changed_in_block_hash?: BlocksBlockHash;

  caused_by_transaction_hash?: TransactionsTransactionHash | null;

  caused_by_receipt_id?: ReceiptsReceiptId | null;

  update_reason?: StateChangeReasonKind;

  affected_account_nonstaked_balance?: string;

  affected_account_staked_balance?: string;

  affected_account_storage_usage?: string;

  index_in_block?: number;
}
