// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.action_kind */
type ActionKind =
  | "CREATE_ACCOUNT"
  | "DEPLOY_CONTRACT"
  | "FUNCTION_CALL"
  | "TRANSFER"
  | "STAKE"
  | "ADD_KEY"
  | "DELETE_KEY"
  | "DELETE_ACCOUNT"
  | "DELEGATE_ACTION";

export default ActionKind;
