// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ReceiptsReceiptId } from "./receipts";

/** Identifier type for public.action_receipt_input_data */
export type ActionReceiptInputDataInputDataId = string & {
  __flavor?: "ActionReceiptInputDataInputDataId";
};

/** Represents the table public.action_receipt_input_data */
export default interface ActionReceiptInputData {
  input_data_id: ActionReceiptInputDataInputDataId;

  input_to_receipt_id: ReceiptsReceiptId;
}

/** Represents the initializer for the table public.action_receipt_input_data */
export interface ActionReceiptInputDataInitializer {
  input_data_id: ActionReceiptInputDataInputDataId;

  input_to_receipt_id: ReceiptsReceiptId;
}

/** Represents the mutator for the table public.action_receipt_input_data */
export interface ActionReceiptInputDataMutator {
  input_data_id?: ActionReceiptInputDataInputDataId;

  input_to_receipt_id?: ReceiptsReceiptId;
}
