// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type ActionKind from "./action-kind";
import type { ReceiptsReceiptId } from "./receipts";

/** Identifier type for public.action_receipt_actions */
export type ActionReceiptActionsIndexInActionReceipt = number & {
  __flavor?: "ActionReceiptActionsIndexInActionReceipt";
};

/** Represents the table public.action_receipt_actions */
export default interface ActionReceiptActions {
  receipt_id: ReceiptsReceiptId;

  index_in_action_receipt: ActionReceiptActionsIndexInActionReceipt;

  action_kind: ActionKind;

  args:
    | {
        public_key: string;
        access_key: {
          nonce: number;
          permission:
            | {
                permission_kind: "FUNCTION_CALL";
                permission_details: {
                  allowance: string;
                  receiver_id: string;
                  method_names: string[];
                };
              }
            | {
                permission_kind: "FULL_ACCESS";
              };
        };
      }
    | {}
    | { beneficiary_id: string }
    | { public_key: string }
    | { code_sha256: string }
    | {
        gas: number;
        deposit: string;
        method_name: string;
        args_json?: Record<string, unknown>;
        args_base64: string;
      }
    | {
        public_key: string;
        stake: string;
      }
    | { deposit: string };

  receipt_predecessor_account_id: string;

  receipt_receiver_account_id: string;

  receipt_included_in_block_timestamp: string;

  is_delegate_action: boolean;

  delegate_parameters: {
    nonce: number;
    sender_id: string;
    receiver_id: string;
    signature: string;
    public_key: string;
    max_block_height: number;
  } | null;

  delegate_parent_index_in_action_receipt: number | null;
}

/** Represents the initializer for the table public.action_receipt_actions */
export interface ActionReceiptActionsInitializer {
  receipt_id: ReceiptsReceiptId;

  index_in_action_receipt: ActionReceiptActionsIndexInActionReceipt;

  action_kind: ActionKind;

  args:
    | {
        public_key: string;
        access_key: {
          nonce: number;
          permission:
            | {
                permission_kind: "FUNCTION_CALL";
                permission_details: {
                  allowance: string;
                  receiver_id: string;
                  method_names: string[];
                };
              }
            | {
                permission_kind: "FULL_ACCESS";
              };
        };
      }
    | {}
    | { beneficiary_id: string }
    | { public_key: string }
    | { code_sha256: string }
    | {
        gas: number;
        deposit: string;
        method_name: string;
        args_json?: Record<string, unknown>;
        args_base64: string;
      }
    | {
        public_key: string;
        stake: string;
      }
    | { deposit: string };

  receipt_predecessor_account_id: string;

  receipt_receiver_account_id: string;

  receipt_included_in_block_timestamp: string;

  is_delegate_action: boolean;

  delegate_parameters?: {
    nonce: number;
    sender_id: string;
    receiver_id: string;
    signature: string;
    public_key: string;
    max_block_height: number;
  } | null;

  delegate_parent_index_in_action_receipt?: number | null;
}

/** Represents the mutator for the table public.action_receipt_actions */
export interface ActionReceiptActionsMutator {
  receipt_id?: ReceiptsReceiptId;

  index_in_action_receipt?: ActionReceiptActionsIndexInActionReceipt;

  action_kind?: ActionKind;

  args?:
    | {
        public_key: string;
        access_key: {
          nonce: number;
          permission:
            | {
                permission_kind: "FUNCTION_CALL";
                permission_details: {
                  allowance: string;
                  receiver_id: string;
                  method_names: string[];
                };
              }
            | {
                permission_kind: "FULL_ACCESS";
              };
        };
      }
    | {}
    | { beneficiary_id: string }
    | { public_key: string }
    | { code_sha256: string }
    | {
        gas: number;
        deposit: string;
        method_name: string;
        args_json?: Record<string, unknown>;
        args_base64: string;
      }
    | {
        public_key: string;
        stake: string;
      }
    | { deposit: string };

  receipt_predecessor_account_id?: string;

  receipt_receiver_account_id?: string;

  receipt_included_in_block_timestamp?: string;

  is_delegate_action?: boolean;

  delegate_parameters?: {
    nonce: number;
    sender_id: string;
    receiver_id: string;
    signature: string;
    public_key: string;
    max_block_height: number;
  } | null;

  delegate_parent_index_in_action_receipt?: number | null;
}
