// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ReceiptsReceiptId } from "./receipts";

/** Represents the table public.action_receipts */
export default interface ActionReceipts {
  receipt_id: ReceiptsReceiptId;

  signer_account_id: string;

  signer_public_key: string;

  gas_price: string;
}

/** Represents the initializer for the table public.action_receipts */
export interface ActionReceiptsInitializer {
  receipt_id: ReceiptsReceiptId;

  signer_account_id: string;

  signer_public_key: string;

  gas_price: string;
}

/** Represents the mutator for the table public.action_receipts */
export interface ActionReceiptsMutator {
  receipt_id?: ReceiptsReceiptId;

  signer_account_id?: string;

  signer_public_key?: string;

  gas_price?: string;
}
