// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type ActionKind from "./action-kind";
import type { ReceiptsReceiptId } from "./receipts";

/** Identifier type for public.action_receipt_actions */
export type ActionReceiptActionsIndexInActionReceipt = number & {
  __flavor?: "ActionReceiptActionsIndexInActionReceipt";
};

/** Represents the table public.action_receipt_actions */
export default interface ActionReceiptActions {
  receipt_id: ReceiptsReceiptId;

  index_in_action_receipt: ActionReceiptActionsIndexInActionReceipt;

  action_kind: ActionKind;

  args: unknown;

  receipt_predecessor_account_id: string;

  receipt_receiver_account_id: string;

  receipt_included_in_block_timestamp: string;
}

/** Represents the initializer for the table public.action_receipt_actions */
export interface ActionReceiptActionsInitializer {
  receipt_id: ReceiptsReceiptId;

  index_in_action_receipt: ActionReceiptActionsIndexInActionReceipt;

  action_kind: ActionKind;

  args: unknown;

  receipt_predecessor_account_id: string;

  receipt_receiver_account_id: string;

  receipt_included_in_block_timestamp: string;
}

/** Represents the mutator for the table public.action_receipt_actions */
export interface ActionReceiptActionsMutator {
  receipt_id?: ReceiptsReceiptId;

  index_in_action_receipt?: ActionReceiptActionsIndexInActionReceipt;

  action_kind?: ActionKind;

  args?: unknown;

  receipt_predecessor_account_id?: string;

  receipt_receiver_account_id?: string;

  receipt_included_in_block_timestamp?: string;
}
