// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ReceiptsReceiptId } from "./receipts";

/** Identifier type for public.action_receipt_output_data */
export type ActionReceiptOutputDataOutputDataId = string & {
  __flavor?: "ActionReceiptOutputDataOutputDataId";
};

/** Represents the table public.action_receipt_output_data */
export default interface ActionReceiptOutputData {
  output_data_id: ActionReceiptOutputDataOutputDataId;

  output_from_receipt_id: ReceiptsReceiptId;

  receiver_account_id: string;
}

/** Represents the initializer for the table public.action_receipt_output_data */
export interface ActionReceiptOutputDataInitializer {
  output_data_id: ActionReceiptOutputDataOutputDataId;

  output_from_receipt_id: ReceiptsReceiptId;

  receiver_account_id: string;
}

/** Represents the mutator for the table public.action_receipt_output_data */
export interface ActionReceiptOutputDataMutator {
  output_data_id?: ActionReceiptOutputDataOutputDataId;

  output_from_receipt_id?: ReceiptsReceiptId;

  receiver_account_id?: string;
}
