// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the view public.aggregated__lockups */
export default interface AggregatedLockups {
  account_id: string;

  creation_block_height: string;

  deletion_block_height: string;
}
