// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { BlocksBlockHash } from "./blocks";

/** Represents the table public.aggregated__circulating_supply */
export default interface AggregatedCirculatingSupply {
  computed_at_block_hash: BlocksBlockHash;

  computed_at_block_timestamp: string;

  circulating_tokens_supply: string;

  total_tokens_supply: string;

  total_lockup_contracts_count: number;

  unfinished_lockup_contracts_count: number;

  foundation_locked_tokens: string;

  lockups_locked_tokens: string;
}

/** Represents the initializer for the table public.aggregated__circulating_supply */
export interface AggregatedCirculatingSupplyInitializer {
  computed_at_block_hash: BlocksBlockHash;

  computed_at_block_timestamp: string;

  circulating_tokens_supply: string;

  total_tokens_supply: string;

  total_lockup_contracts_count: number;

  unfinished_lockup_contracts_count: number;

  foundation_locked_tokens: string;

  lockups_locked_tokens: string;
}

/** Represents the mutator for the table public.aggregated__circulating_supply */
export interface AggregatedCirculatingSupplyMutator {
  computed_at_block_hash?: BlocksBlockHash;

  computed_at_block_timestamp?: string;

  circulating_tokens_supply?: string;

  total_tokens_supply?: string;

  total_lockup_contracts_count?: number;

  unfinished_lockup_contracts_count?: number;

  foundation_locked_tokens?: string;

  lockups_locked_tokens?: string;
}
