// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type FtEventKind from "./ft-event-kind";
import type { ReceiptsReceiptId } from "./receipts";

/** Identifier type for public.assets__fungible_token_events */
export type AssetsFungibleTokenEventsEmittedIndexOfEventEntryInShard =
  number & {
    __flavor?: "AssetsFungibleTokenEventsEmittedIndexOfEventEntryInShard";
  };

/** Represents the table public.assets__fungible_token_events */
export default interface AssetsFungibleTokenEvents {
  emitted_for_receipt_id: ReceiptsReceiptId;

  emitted_index_of_event_entry_in_shard: AssetsFungibleTokenEventsEmittedIndexOfEventEntryInShard;

  emitted_at_block_timestamp: string;

  emitted_in_shard_id: string;

  emitted_by_contract_account_id: string;

  amount: string;

  event_kind: FtEventKind;

  token_old_owner_account_id: string;

  token_new_owner_account_id: string;

  event_memo: string;
}

/** Represents the initializer for the table public.assets__fungible_token_events */
export interface AssetsFungibleTokenEventsInitializer {
  emitted_for_receipt_id: ReceiptsReceiptId;

  emitted_index_of_event_entry_in_shard: AssetsFungibleTokenEventsEmittedIndexOfEventEntryInShard;

  emitted_at_block_timestamp: string;

  emitted_in_shard_id: string;

  emitted_by_contract_account_id: string;

  amount: string;

  event_kind: FtEventKind;

  /** Default value: ''::text */
  token_old_owner_account_id?: string;

  /** Default value: ''::text */
  token_new_owner_account_id?: string;

  /** Default value: ''::text */
  event_memo?: string;
}

/** Represents the mutator for the table public.assets__fungible_token_events */
export interface AssetsFungibleTokenEventsMutator {
  emitted_for_receipt_id?: ReceiptsReceiptId;

  emitted_index_of_event_entry_in_shard?: AssetsFungibleTokenEventsEmittedIndexOfEventEntryInShard;

  emitted_at_block_timestamp?: string;

  emitted_in_shard_id?: string;

  emitted_by_contract_account_id?: string;

  amount?: string;

  event_kind?: FtEventKind;

  token_old_owner_account_id?: string;

  token_new_owner_account_id?: string;

  event_memo?: string;
}
