// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.blocks */
export type BlocksBlockHash = string & { __flavor?: "BlocksBlockHash" };

/** Represents the table public.blocks */
export default interface Blocks {
  block_hash: BlocksBlockHash;

  block_height: string;

  prev_block_hash: string;

  block_timestamp: string;

  total_supply: string;

  gas_price: string;

  author_account_id: string;
}

/** Represents the initializer for the table public.blocks */
export interface BlocksInitializer {
  block_hash: BlocksBlockHash;

  block_height: string;

  prev_block_hash: string;

  block_timestamp: string;

  total_supply: string;

  gas_price: string;

  author_account_id: string;
}

/** Represents the mutator for the table public.blocks */
export interface BlocksMutator {
  block_hash?: BlocksBlockHash;

  block_height?: string;

  prev_block_hash?: string;

  block_timestamp?: string;

  total_supply?: string;

  gas_price?: string;

  author_account_id?: string;
}
