// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { BlocksBlockHash } from "./blocks";

/** Identifier type for public.chunks */
export type ChunksChunkHash = string & { __flavor?: "ChunksChunkHash" };

/** Represents the table public.chunks */
export default interface Chunks {
  chunk_hash: ChunksChunkHash;

  included_in_block_hash: BlocksBlockHash;

  shard_id: string;

  signature: string;

  gas_limit: string;

  gas_used: string;

  author_account_id: string;
}

/** Represents the initializer for the table public.chunks */
export interface ChunksInitializer {
  chunk_hash: ChunksChunkHash;

  included_in_block_hash: BlocksBlockHash;

  shard_id: string;

  signature: string;

  gas_limit: string;

  gas_used: string;

  author_account_id: string;
}

/** Represents the mutator for the table public.chunks */
export interface ChunksMutator {
  chunk_hash?: ChunksChunkHash;

  included_in_block_hash?: BlocksBlockHash;

  shard_id?: string;

  signature?: string;

  gas_limit?: string;

  gas_used?: string;

  author_account_id?: string;
}
