// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ReceiptsReceiptId } from "./receipts";

/** Identifier type for public.data_receipts */
export type DataReceiptsDataId = string & { __flavor?: "DataReceiptsDataId" };

/** Represents the table public.data_receipts */
export default interface DataReceipts {
  data_id: DataReceiptsDataId;

  receipt_id: ReceiptsReceiptId;

  data: unknown | null;
}

/** Represents the initializer for the table public.data_receipts */
export interface DataReceiptsInitializer {
  data_id: DataReceiptsDataId;

  receipt_id: ReceiptsReceiptId;

  data?: unknown | null;
}

/** Represents the mutator for the table public.data_receipts */
export interface DataReceiptsMutator {
  data_id?: DataReceiptsDataId;

  receipt_id?: ReceiptsReceiptId;

  data?: unknown | null;
}
