// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ReceiptsReceiptId } from "./receipts";

/** Identifier type for public.execution_outcome_receipts */
export type ExecutionOutcomeReceiptsIndexInExecutionOutcome = number & {
  __flavor?: "ExecutionOutcomeReceiptsIndexInExecutionOutcome";
};

/** Identifier type for public.execution_outcome_receipts */
export type ExecutionOutcomeReceiptsProducedReceiptId = string & {
  __flavor?: "ExecutionOutcomeReceiptsProducedReceiptId";
};

/** Represents the table public.execution_outcome_receipts */
export default interface ExecutionOutcomeReceipts {
  executed_receipt_id: ReceiptsReceiptId;

  index_in_execution_outcome: ExecutionOutcomeReceiptsIndexInExecutionOutcome;

  produced_receipt_id: ExecutionOutcomeReceiptsProducedReceiptId;
}

/** Represents the initializer for the table public.execution_outcome_receipts */
export interface ExecutionOutcomeReceiptsInitializer {
  executed_receipt_id: ReceiptsReceiptId;

  index_in_execution_outcome: ExecutionOutcomeReceiptsIndexInExecutionOutcome;

  produced_receipt_id: ExecutionOutcomeReceiptsProducedReceiptId;
}

/** Represents the mutator for the table public.execution_outcome_receipts */
export interface ExecutionOutcomeReceiptsMutator {
  executed_receipt_id?: ReceiptsReceiptId;

  index_in_execution_outcome?: ExecutionOutcomeReceiptsIndexInExecutionOutcome;

  produced_receipt_id?: ExecutionOutcomeReceiptsProducedReceiptId;
}
