// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.execution_outcome_status */
type ExecutionOutcomeStatus =
  | "UNKNOWN"
  | "FAILURE"
  | "SUCCESS_VALUE"
  | "SUCCESS_RECEIPT_ID";

export default ExecutionOutcomeStatus;
