// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { BlocksBlockHash } from "./blocks";
import type ExecutionOutcomeStatus from "./execution-outcome-status";
import type { ReceiptsReceiptId } from "./receipts";

/** Represents the table public.execution_outcomes */
export default interface ExecutionOutcomes {
  receipt_id: ReceiptsReceiptId;

  executed_in_block_hash: BlocksBlockHash;

  executed_in_block_timestamp: string;

  index_in_chunk: number;

  gas_burnt: string;

  tokens_burnt: string;

  executor_account_id: string;

  status: ExecutionOutcomeStatus;

  shard_id: string;
}

/** Represents the initializer for the table public.execution_outcomes */
export interface ExecutionOutcomesInitializer {
  receipt_id: ReceiptsReceiptId;

  executed_in_block_hash: BlocksBlockHash;

  executed_in_block_timestamp: string;

  index_in_chunk: number;

  gas_burnt: string;

  tokens_burnt: string;

  executor_account_id: string;

  status: ExecutionOutcomeStatus;

  shard_id: string;
}

/** Represents the mutator for the table public.execution_outcomes */
export interface ExecutionOutcomesMutator {
  receipt_id?: ReceiptsReceiptId;

  executed_in_block_hash?: BlocksBlockHash;

  executed_in_block_timestamp?: string;

  index_in_chunk?: number;

  gas_burnt?: string;

  tokens_burnt?: string;

  executor_account_id?: string;

  status?: ExecutionOutcomeStatus;

  shard_id?: string;
}
