// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.ft_event_kind */
type FtEventKind = "MINT" | "TRANSFER" | "BURN";

export default FtEventKind;
