// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.nft_event_kind */
type NftEventKind = "MINT" | "TRANSFER" | "BURN";

export default NftEventKind;
