// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.receipt_kind */
type ReceiptKind = "ACTION" | "DATA";

export default ReceiptKind;
