// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { BlocksBlockHash } from "./blocks";
import type { ChunksChunkHash } from "./chunks";
import type ReceiptKind from "./receipt-kind";
import type { TransactionsTransactionHash } from "./transactions";

/** Identifier type for public.receipts */
export type ReceiptsReceiptId = string & { __flavor?: "ReceiptsReceiptId" };

/** Represents the table public.receipts */
export default interface Receipts {
  receipt_id: ReceiptsReceiptId;

  included_in_block_hash: BlocksBlockHash;

  included_in_chunk_hash: ChunksChunkHash;

  index_in_chunk: number;

  included_in_block_timestamp: string;

  predecessor_account_id: string;

  receiver_account_id: string;

  receipt_kind: ReceiptKind;

  originated_from_transaction_hash: TransactionsTransactionHash;
}

/** Represents the initializer for the table public.receipts */
export interface ReceiptsInitializer {
  receipt_id: ReceiptsReceiptId;

  included_in_block_hash: BlocksBlockHash;

  included_in_chunk_hash: ChunksChunkHash;

  index_in_chunk: number;

  included_in_block_timestamp: string;

  predecessor_account_id: string;

  receiver_account_id: string;

  receipt_kind: ReceiptKind;

  originated_from_transaction_hash: TransactionsTransactionHash;
}

/** Represents the mutator for the table public.receipts */
export interface ReceiptsMutator {
  receipt_id?: ReceiptsReceiptId;

  included_in_block_hash?: BlocksBlockHash;

  included_in_chunk_hash?: ChunksChunkHash;

  index_in_chunk?: number;

  included_in_block_timestamp?: string;

  predecessor_account_id?: string;

  receiver_account_id?: string;

  receipt_kind?: ReceiptKind;

  originated_from_transaction_hash?: TransactionsTransactionHash;
}
