// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.state_change_reason_kind */
type StateChangeReasonKind =
  | "TRANSACTION_PROCESSING"
  | "ACTION_RECEIPT_PROCESSING_STARTED"
  | "ACTION_RECEIPT_GAS_REWARD"
  | "RECEIPT_PROCESSING"
  | "POSTPONED_RECEIPT"
  | "UPDATED_DELAYED_RECEIPTS"
  | "VALIDATOR_ACCOUNTS_UPDATE"
  | "MIGRATION";

export default StateChangeReasonKind;
