// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type ActionKind from "./action-kind";
import type { TransactionsTransactionHash } from "./transactions";

/** Identifier type for public.transaction_actions */
export type TransactionActionsIndexInTransaction = number & {
  __flavor?: "TransactionActionsIndexInTransaction";
};

/** Represents the table public.transaction_actions */
export default interface TransactionActions {
  transaction_hash: TransactionsTransactionHash;

  index_in_transaction: TransactionActionsIndexInTransaction;

  action_kind: ActionKind;

  args: unknown;
}

/** Represents the initializer for the table public.transaction_actions */
export interface TransactionActionsInitializer {
  transaction_hash: TransactionsTransactionHash;

  index_in_transaction: TransactionActionsIndexInTransaction;

  action_kind: ActionKind;

  args: unknown;
}

/** Represents the mutator for the table public.transaction_actions */
export interface TransactionActionsMutator {
  transaction_hash?: TransactionsTransactionHash;

  index_in_transaction?: TransactionActionsIndexInTransaction;

  action_kind?: ActionKind;

  args?: unknown;
}
