// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { BlocksBlockHash } from "./blocks";
import type { ChunksChunkHash } from "./chunks";
import type ExecutionOutcomeStatus from "./execution-outcome-status";

/** Identifier type for public.transactions */
export type TransactionsTransactionHash = string & {
  __flavor?: "TransactionsTransactionHash";
};

/** Represents the table public.transactions */
export default interface Transactions {
  transaction_hash: TransactionsTransactionHash;

  included_in_block_hash: BlocksBlockHash;

  included_in_chunk_hash: ChunksChunkHash;

  index_in_chunk: number;

  block_timestamp: string;

  signer_account_id: string;

  signer_public_key: string;

  nonce: string;

  receiver_account_id: string;

  signature: string;

  status: ExecutionOutcomeStatus;

  converted_into_receipt_id: string;

  receipt_conversion_gas_burnt: string | null;

  receipt_conversion_tokens_burnt: string | null;
}

/** Represents the initializer for the table public.transactions */
export interface TransactionsInitializer {
  transaction_hash: TransactionsTransactionHash;

  included_in_block_hash: BlocksBlockHash;

  included_in_chunk_hash: ChunksChunkHash;

  index_in_chunk: number;

  block_timestamp: string;

  signer_account_id: string;

  signer_public_key: string;

  nonce: string;

  receiver_account_id: string;

  signature: string;

  status: ExecutionOutcomeStatus;

  converted_into_receipt_id: string;

  receipt_conversion_gas_burnt?: string | null;

  receipt_conversion_tokens_burnt?: string | null;
}

/** Represents the mutator for the table public.transactions */
export interface TransactionsMutator {
  transaction_hash?: TransactionsTransactionHash;

  included_in_block_hash?: BlocksBlockHash;

  included_in_chunk_hash?: ChunksChunkHash;

  index_in_chunk?: number;

  block_timestamp?: string;

  signer_account_id?: string;

  signer_public_key?: string;

  nonce?: string;

  receiver_account_id?: string;

  signature?: string;

  status?: ExecutionOutcomeStatus;

  converted_into_receipt_id?: string;

  receipt_conversion_gas_burnt?: string | null;

  receipt_conversion_tokens_burnt?: string | null;
}
