steps:

  - label: publish docker
    command: ./scripts/docker-release.sh explorer-wamp wamp
    branches: "master"
    plugins:
    - docker-login#v2.0.1:
        username: nearprotocol
        password-env: DOCKER_LOGIN_PASSWORD

  - label: publish docker
    command: ./scripts/docker-release.sh explorer-backend backend
    branches: "master"
    plugins:
    - docker-login#v2.0.1:
        username: nearprotocol
        password-env: DOCKER_LOGIN_PASSWORD

  - label: publish docker
    command: ./scripts/docker-release.sh explorer-frontend frontend
    branches: "master"
    plugins:
    - docker-login#v2.0.1:
        username: nearprotocol
        password-env: DOCKER_LOGIN_PASSWORD
