import React, { useState, useEffect } from "react";
import ReactEcharts from "echarts-for-react";
import * as echarts from "echarts";
import { Tabs, Tab } from "react-bootstrap";
import { useTranslation } from "react-i18next";

import { AccountsByDate } from "../../libraries/explorer-wamp/stats";

import { Props } from "./TransactionsByDate";

const ActiveNearAppsUsersByDate = ({ chartStyle }: Props) => {
  const { t } = useTranslation();
  const [activeAccountsByWeek, setWeekAccounts] = useState(Array());
  const [week, setWeek] = useState(Array());

  useEffect(() => {
    // TODO(sparkyrider): Put a proper implementation in near-analytics after User Activity NEP lands and get implemented on indexer-for-explorer side.
    // Meanwhile, @sparkyrider will manually submit the new values weekly in PRs to NEAR Explorer.
    // XXX: Hardcoded values were generated by this query:
    // select to_timestamp(receipt_included_in_block_timestamp / 1000000000)::date as date
    //  ,count(*) as accountscount
    //  from action_receipt_actions
    // where receipt_receiver_account_id = 'v1.nearapps.near'
    //   and to_timestamp(receipt_included_in_block_timestamp / 1000000000) > NOW() - interval '60 days'
    // group by to_timestamp(receipt_included_in_block_timestamp / 1000000000)::Date;
    let accounts = [
      {
        date: "2022-01-02 23:59:59",
        accountsCount: 214,
      },
      {
        date: "2021-01-12 23:59:59",
        accountsCount: 277,
      },
      {
        date: "2021-12-19 23:59:59",
        accountsCount: 7902,
      },
      {
        date: "2021-12-26 23:59:59",
        accountsCount: 220,
      },
      {
        date: "2022-01-02 23:59:59",
        accountsCount: 214,
      },
      {
        date: "2022-01-09 23:59:59",
        accountsCount: 204774,
      },
      {
        date: "2022-01-16 23:59:59",
        accountsCount: 393725,
      },
      {
        date: "2022-01-23 23:59:59",
        accountsCount: 30946,
      },
    ];
    if (accounts) {
      const newAccounts = accounts.map((account: AccountsByDate) =>
        Number(account.accountsCount)
      );
      const week = accounts.map((account: AccountsByDate) =>
        account.date.slice(0, 10)
      );
      setWeekAccounts(newAccounts);
      setWeek(week);
    }
  }, []);

  const getOption = (
    title: string,
    seriesName: string,
    data: Array<number>,
    date: Array<string>
  ) => {
    return {
      title: {
        text: title,
        subtext: t(
          "component.stats.ActiveNearAppsUsersByDate.nearapps_details_link_text"
        ),
        sublink: "https://primelab.io",
      },
      tooltip: {
        trigger: "axis",
      },
      grid: {
        left: "3%",
        right: "4%",
        bottom: "3%",
        containLabel: true,
        backgroundColor: "#F9F9F9",
        show: true,
        color: "white",
      },
      xAxis: [
        {
          type: "category",
          boundaryGap: false,
          data: date,
        },
      ],
      yAxis: [
        {
          type: "value",
          splitLine: {
            lineStyle: {
              color: "white",
            },
          },
        },
      ],
      dataZoom: [
        {
          type: "inside",
          start: 0,
          end: 100,
          filterMode: "filter",
        },
        {
          start: 0,
          end: 100,
        },
      ],
      series: [
        {
          name: seriesName,
          type: "line",
          lineStyle: {
            color: "#04a7bf",
            width: 2,
          },
          symbol: "circle",
          itemStyle: {
            color: "#25272A",
          },
          areaStyle: {
            color: new echarts.graphic.LinearGradient(0, 0, 0, 1, [
              {
                offset: 0,
                color: "rgb(4, 167, 191)",
              },
              {
                offset: 1,
                color: "rgb(201, 248, 255)",
              },
            ]),
          },
          data: data,
        },
      ],
    };
  };

  return (
    <ReactEcharts
      option={getOption(
        t(
          "component.stats.ActiveNearAppsUsersByDate.weekly_number_of_active_nearapps_users"
        ),
        t("component.stats.ActiveNearAppsUsersByDate.active_nearapps_users"),
        activeAccountsByWeek,
        week
      )}
      style={chartStyle}
    />
  );
};

export default ActiveNearAppsUsersByDate;
