// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.balance_changes */
export type BalanceChangesBlockTimestamp = string & {
  __flavor?: "BalanceChangesBlockTimestamp";
};

/** Identifier type for public.balance_changes */
export type BalanceChangesShardId = number & {
  __flavor?: "BalanceChangesShardId";
};

/** Identifier type for public.balance_changes */
export type BalanceChangesIndexInChunk = number & {
  __flavor?: "BalanceChangesIndexInChunk";
};

/** Represents the table public.balance_changes */
export default interface BalanceChanges {
  block_timestamp: BalanceChangesBlockTimestamp;

  shard_id: BalanceChangesShardId;

  index_in_chunk: BalanceChangesIndexInChunk;

  receipt_id: string | null;

  transaction_hash: string | null;

  affected_account_id: string;

  involved_account_id: string | null;

  direction: string;

  cause: string;

  status: string;

  delta_nonstaked_amount: string;

  absolute_nonstaked_amount: string;

  delta_staked_amount: string;

  absolute_staked_amount: string;

  event_index: string;
}

/** Represents the initializer for the table public.balance_changes */
export interface BalanceChangesInitializer {
  block_timestamp: BalanceChangesBlockTimestamp;

  shard_id: BalanceChangesShardId;

  index_in_chunk: BalanceChangesIndexInChunk;

  receipt_id?: string | null;

  transaction_hash?: string | null;

  affected_account_id: string;

  involved_account_id?: string | null;

  direction: string;

  cause: string;

  status: string;

  delta_nonstaked_amount: string;

  absolute_nonstaked_amount: string;

  delta_staked_amount: string;

  absolute_staked_amount: string;

  /** Default value: 0 */
  event_index?: string;
}

/** Represents the mutator for the table public.balance_changes */
export interface BalanceChangesMutator {
  block_timestamp?: BalanceChangesBlockTimestamp;

  shard_id?: BalanceChangesShardId;

  index_in_chunk?: BalanceChangesIndexInChunk;

  receipt_id?: string | null;

  transaction_hash?: string | null;

  affected_account_id?: string;

  involved_account_id?: string | null;

  direction?: string;

  cause?: string;

  status?: string;

  delta_nonstaked_amount?: string;

  absolute_nonstaked_amount?: string;

  delta_staked_amount?: string;

  absolute_staked_amount?: string;

  event_index?: string;
}
