// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type {
  default as BalanceChanges,
  BalanceChangesInitializer,
  BalanceChangesMutator,
} from "./balance-changes";

export type {
  default as BalanceChanges,
  BalanceChangesInitializer,
  BalanceChangesMutator,
  BalanceChangesBlockTimestamp,
  BalanceChangesShardId,
  BalanceChangesIndexInChunk,
} from "./balance-changes";

export interface SelectorModelTypeMap {
  balance_changes: BalanceChanges;
}

export interface InitializerModelTypeMap {
  balance_changes: BalanceChangesInitializer;
}

export interface MutatorModelTypeMap {
  balance_changes: BalanceChangesMutator;
}
