steps:
  # Build the Frontend
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-f",
        "frontend/Dockerfile",
        "-t",
        "${_IMAGE}:${_PR_NUMBER}",
        ".",
      ]
  # Push Frontend to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "${_IMAGE}:${_PR_NUMBER}"]
  # Deploy Frontend
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "explorer-frontend"
      - "--image"
      - "${_IMAGE}:${_PR_NUMBER}"
      - "--region"
      - "us-central1"
      - "--tag"
      - "pr-${_PR_NUMBER}"
      - "--update-env-vars"
      - "NEAR_EXPLORER_CONFIG__BACKEND__HOSTS__TESTNET=pr-${_PR_NUMBER}---explorer-backend-testnet-vcqilefdcq-uc.a.run.app"
      - "--update-env-vars"
      - "NEAR_EXPLORER_CONFIG__BACKEND__HOSTS__MAINNET=pr-${_PR_NUMBER}---explorer-backend-mainnet-vcqilefdcq-uc.a.run.app"
      - "--update-env-vars"
      - "BRANCH=${_BRANCH}"
      - "--update-env-vars"
      - "COMMIT_SHA=${_COMMIT_SHA}"
