steps:
  # Build the Frontend
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-f",
        "frontend/Dockerfile",
        "-t",
        "us-central1-docker.pkg.dev/pagoda-data-stack-dev/cloud-run-source-deploy/explorer-frontend:${_PR_NUMBER}",
        ".",
      ]
  # Push Frontend to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-central1-docker.pkg.dev/pagoda-data-stack-dev/cloud-run-source-deploy/explorer-frontend:${_PR_NUMBER}",
      ]
  # Deploy Frontend
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "explorer-frontend"
      - "--image"
      - "us-central1-docker.pkg.dev/pagoda-data-stack-dev/cloud-run-source-deploy/explorer-frontend:${_PR_NUMBER}"
      - "--region"
      - "us-central1"
      - "--tag"
      - "pr-${_PR_NUMBER}"
      - "--update-env-vars"
      - "NEAR_EXPLORER_CONFIG__BACKEND__HOSTS__TESTNET=from-github---explorer-backend-testnet-vcqilefdcq-uc.a.run.app"
      - "--update-env-vars"
      - "NEAR_EXPLORER_CONFIG__BACKEND__HOSTS__MAINNET=from-github---explorer-backend-mainnet-vcqilefdcq-uc.a.run.app"
