steps:
  # Deploy Backend Testnet
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "explorer-backend-testnet",
        "--image",
        "us-central1-docker.pkg.dev/pagoda-data-stack-dev/cloud-run-source-deploy/explorer-backend:${_PR_NUMBER}",
        "--region",
        "us-central1",
        "--tag",
        "pr-${_PR_NUMBER}",
      ]
