// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.daily_receipts_per_contract_count */
export type DailyReceiptsPerContractCountCollectedForDay = Date & {
  __flavor?: "DailyReceiptsPerContractCountCollectedForDay";
};

/** Identifier type for public.daily_receipts_per_contract_count */
export type DailyReceiptsPerContractCountContractId = string & {
  __flavor?: "DailyReceiptsPerContractCountContractId";
};

/** Represents the table public.daily_receipts_per_contract_count */
export default interface DailyReceiptsPerContractCount {
  collected_for_day: DailyReceiptsPerContractCountCollectedForDay;

  contract_id: DailyReceiptsPerContractCountContractId;

  receipts_count: string;
}

/** Represents the initializer for the table public.daily_receipts_per_contract_count */
export interface DailyReceiptsPerContractCountInitializer {
  collected_for_day: DailyReceiptsPerContractCountCollectedForDay;

  contract_id: DailyReceiptsPerContractCountContractId;

  receipts_count: string;
}

/** Represents the mutator for the table public.daily_receipts_per_contract_count */
export interface DailyReceiptsPerContractCountMutator {
  collected_for_day?: DailyReceiptsPerContractCountCollectedForDay;

  contract_id?: DailyReceiptsPerContractCountContractId;

  receipts_count?: string;
}
