// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.daily_transaction_count_by_gas_burnt_ranges */
export type DailyTransactionCountByGasBurntRangesCollectedForDay = Date & {
  __flavor?: "DailyTransactionCountByGasBurntRangesCollectedForDay";
};

/** Identifier type for public.daily_transaction_count_by_gas_burnt_ranges */
export type DailyTransactionCountByGasBurntRangesTopOfRangeInTeragas =
  number & {
    __flavor?: "DailyTransactionCountByGasBurntRangesTopOfRangeInTeragas";
  };

/** Represents the table public.daily_transaction_count_by_gas_burnt_ranges */
export default interface DailyTransactionCountByGasBurntRanges {
  collected_for_day: DailyTransactionCountByGasBurntRangesCollectedForDay;

  top_of_range_in_teragas: DailyTransactionCountByGasBurntRangesTopOfRangeInTeragas;

  transactions_count: string;
}

/** Represents the initializer for the table public.daily_transaction_count_by_gas_burnt_ranges */
export interface DailyTransactionCountByGasBurntRangesInitializer {
  collected_for_day: DailyTransactionCountByGasBurntRangesCollectedForDay;

  top_of_range_in_teragas: DailyTransactionCountByGasBurntRangesTopOfRangeInTeragas;

  transactions_count: string;
}

/** Represents the mutator for the table public.daily_transaction_count_by_gas_burnt_ranges */
export interface DailyTransactionCountByGasBurntRangesMutator {
  collected_for_day?: DailyTransactionCountByGasBurntRangesCollectedForDay;

  top_of_range_in_teragas?: DailyTransactionCountByGasBurntRangesTopOfRangeInTeragas;

  transactions_count?: string;
}
