// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.daily_ingoing_transactions_per_account_count */
export type DailyIngoingTransactionsPerAccountCountCollectedForDay = Date & {
  __flavor?: "DailyIngoingTransactionsPerAccountCountCollectedForDay";
};

/** Identifier type for public.daily_ingoing_transactions_per_account_count */
export type DailyIngoingTransactionsPerAccountCountAccountId = string & {
  __flavor?: "DailyIngoingTransactionsPerAccountCountAccountId";
};

/** Represents the table public.daily_ingoing_transactions_per_account_count */
export default interface DailyIngoingTransactionsPerAccountCount {
  collected_for_day: DailyIngoingTransactionsPerAccountCountCollectedForDay;

  account_id: DailyIngoingTransactionsPerAccountCountAccountId;

  ingoing_transactions_count: string;
}

/** Represents the initializer for the table public.daily_ingoing_transactions_per_account_count */
export interface DailyIngoingTransactionsPerAccountCountInitializer {
  collected_for_day: DailyIngoingTransactionsPerAccountCountCollectedForDay;

  account_id: DailyIngoingTransactionsPerAccountCountAccountId;

  ingoing_transactions_count: string;
}

/** Represents the mutator for the table public.daily_ingoing_transactions_per_account_count */
export interface DailyIngoingTransactionsPerAccountCountMutator {
  collected_for_day?: DailyIngoingTransactionsPerAccountCountCollectedForDay;

  account_id?: DailyIngoingTransactionsPerAccountCountAccountId;

  ingoing_transactions_count?: string;
}
