// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.daily_tokens_spent_on_fees */
export type DailyTokensSpentOnFeesCollectedForDay = Date & {
  __flavor?: "DailyTokensSpentOnFeesCollectedForDay";
};

/** Represents the table public.daily_tokens_spent_on_fees */
export default interface DailyTokensSpentOnFees {
  collected_for_day: DailyTokensSpentOnFeesCollectedForDay;

  tokens_spent_on_fees: string;
}

/** Represents the initializer for the table public.daily_tokens_spent_on_fees */
export interface DailyTokensSpentOnFeesInitializer {
  collected_for_day: DailyTokensSpentOnFeesCollectedForDay;

  tokens_spent_on_fees: string;
}

/** Represents the mutator for the table public.daily_tokens_spent_on_fees */
export interface DailyTokensSpentOnFeesMutator {
  collected_for_day?: DailyTokensSpentOnFeesCollectedForDay;

  tokens_spent_on_fees?: string;
}
