// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.daily_new_accounts_per_ecosystem_entity_count */
export type DailyNewAccountsPerEcosystemEntityCountCollectedForDay = Date & {
  __flavor?: "DailyNewAccountsPerEcosystemEntityCountCollectedForDay";
};

/** Identifier type for public.daily_new_accounts_per_ecosystem_entity_count */
export type DailyNewAccountsPerEcosystemEntityCountEntityId = string & {
  __flavor?: "DailyNewAccountsPerEcosystemEntityCountEntityId";
};

/** Represents the table public.daily_new_accounts_per_ecosystem_entity_count */
export default interface DailyNewAccountsPerEcosystemEntityCount {
  collected_for_day: DailyNewAccountsPerEcosystemEntityCountCollectedForDay;

  entity_id: DailyNewAccountsPerEcosystemEntityCountEntityId;

  new_accounts_count: string;
}

/** Represents the initializer for the table public.daily_new_accounts_per_ecosystem_entity_count */
export interface DailyNewAccountsPerEcosystemEntityCountInitializer {
  collected_for_day: DailyNewAccountsPerEcosystemEntityCountCollectedForDay;

  entity_id: DailyNewAccountsPerEcosystemEntityCountEntityId;

  new_accounts_count: string;
}

/** Represents the mutator for the table public.daily_new_accounts_per_ecosystem_entity_count */
export interface DailyNewAccountsPerEcosystemEntityCountMutator {
  collected_for_day?: DailyNewAccountsPerEcosystemEntityCountCollectedForDay;

  entity_id?: DailyNewAccountsPerEcosystemEntityCountEntityId;

  new_accounts_count?: string;
}
