// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.daily_outgoing_transactions_per_account_count */
export type DailyOutgoingTransactionsPerAccountCountCollectedForDay = Date & {
  __flavor?: "DailyOutgoingTransactionsPerAccountCountCollectedForDay";
};

/** Identifier type for public.daily_outgoing_transactions_per_account_count */
export type DailyOutgoingTransactionsPerAccountCountAccountId = string & {
  __flavor?: "DailyOutgoingTransactionsPerAccountCountAccountId";
};

/** Represents the table public.daily_outgoing_transactions_per_account_count */
export default interface DailyOutgoingTransactionsPerAccountCount {
  collected_for_day: DailyOutgoingTransactionsPerAccountCountCollectedForDay;

  account_id: DailyOutgoingTransactionsPerAccountCountAccountId;

  outgoing_transactions_count: string;
}

/** Represents the initializer for the table public.daily_outgoing_transactions_per_account_count */
export interface DailyOutgoingTransactionsPerAccountCountInitializer {
  collected_for_day: DailyOutgoingTransactionsPerAccountCountCollectedForDay;

  account_id: DailyOutgoingTransactionsPerAccountCountAccountId;

  outgoing_transactions_count: string;
}

/** Represents the mutator for the table public.daily_outgoing_transactions_per_account_count */
export interface DailyOutgoingTransactionsPerAccountCountMutator {
  collected_for_day?: DailyOutgoingTransactionsPerAccountCountCollectedForDay;

  account_id?: DailyOutgoingTransactionsPerAccountCountAccountId;

  outgoing_transactions_count?: string;
}
