// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.daily_deleted_accounts_count */
export type DailyDeletedAccountsCountCollectedForDay = Date & {
  __flavor?: "DailyDeletedAccountsCountCollectedForDay";
};

/** Represents the table public.daily_deleted_accounts_count */
export default interface DailyDeletedAccountsCount {
  collected_for_day: DailyDeletedAccountsCountCollectedForDay;

  deleted_accounts_count: number;
}

/** Represents the initializer for the table public.daily_deleted_accounts_count */
export interface DailyDeletedAccountsCountInitializer {
  collected_for_day: DailyDeletedAccountsCountCollectedForDay;

  deleted_accounts_count: number;
}

/** Represents the mutator for the table public.daily_deleted_accounts_count */
export interface DailyDeletedAccountsCountMutator {
  collected_for_day?: DailyDeletedAccountsCountCollectedForDay;

  deleted_accounts_count?: number;
}
