// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.daily_transactions_count */
export type DailyTransactionsCountCollectedForDay = Date & {
  __flavor?: "DailyTransactionsCountCollectedForDay";
};

/** Represents the table public.daily_transactions_count */
export default interface DailyTransactionsCount {
  collected_for_day: DailyTransactionsCountCollectedForDay;

  transactions_count: string;
}

/** Represents the initializer for the table public.daily_transactions_count */
export interface DailyTransactionsCountInitializer {
  collected_for_day: DailyTransactionsCountCollectedForDay;

  transactions_count: string;
}

/** Represents the mutator for the table public.daily_transactions_count */
export interface DailyTransactionsCountMutator {
  collected_for_day?: DailyTransactionsCountCollectedForDay;

  transactions_count?: string;
}
