// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.daily_new_accounts_count */
export type DailyNewAccountsCountCollectedForDay = Date & {
  __flavor?: "DailyNewAccountsCountCollectedForDay";
};

/** Represents the table public.daily_new_accounts_count */
export default interface DailyNewAccountsCount {
  collected_for_day: DailyNewAccountsCountCollectedForDay;

  new_accounts_count: number;
}

/** Represents the initializer for the table public.daily_new_accounts_count */
export interface DailyNewAccountsCountInitializer {
  collected_for_day: DailyNewAccountsCountCollectedForDay;

  new_accounts_count: number;
}

/** Represents the mutator for the table public.daily_new_accounts_count */
export interface DailyNewAccountsCountMutator {
  collected_for_day?: DailyNewAccountsCountCollectedForDay;

  new_accounts_count?: number;
}
