// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.daily_new_unique_contracts_count */
export type DailyNewUniqueContractsCountCollectedForDay = Date & {
  __flavor?: "DailyNewUniqueContractsCountCollectedForDay";
};

/** Represents the table public.daily_new_unique_contracts_count */
export default interface DailyNewUniqueContractsCount {
  collected_for_day: DailyNewUniqueContractsCountCollectedForDay;

  new_unique_contracts_count: number;
}

/** Represents the initializer for the table public.daily_new_unique_contracts_count */
export interface DailyNewUniqueContractsCountInitializer {
  collected_for_day: DailyNewUniqueContractsCountCollectedForDay;

  new_unique_contracts_count: number;
}

/** Represents the mutator for the table public.daily_new_unique_contracts_count */
export interface DailyNewUniqueContractsCountMutator {
  collected_for_day?: DailyNewUniqueContractsCountCollectedForDay;

  new_unique_contracts_count?: number;
}
