// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.daily_new_contracts_count */
export type DailyNewContractsCountCollectedForDay = Date & {
  __flavor?: "DailyNewContractsCountCollectedForDay";
};

/** Represents the table public.daily_new_contracts_count */
export default interface DailyNewContractsCount {
  collected_for_day: DailyNewContractsCountCollectedForDay;

  new_contracts_count: number;
}

/** Represents the initializer for the table public.daily_new_contracts_count */
export interface DailyNewContractsCountInitializer {
  collected_for_day: DailyNewContractsCountCollectedForDay;

  new_contracts_count: number;
}

/** Represents the mutator for the table public.daily_new_contracts_count */
export interface DailyNewContractsCountMutator {
  collected_for_day?: DailyNewContractsCountCollectedForDay;

  new_contracts_count?: number;
}
