// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.daily_deposit_amount */
export type DailyDepositAmountCollectedForDay = Date & {
  __flavor?: "DailyDepositAmountCollectedForDay";
};

/** Represents the table public.daily_deposit_amount */
export default interface DailyDepositAmount {
  collected_for_day: DailyDepositAmountCollectedForDay;

  deposit_amount: string;
}

/** Represents the initializer for the table public.daily_deposit_amount */
export interface DailyDepositAmountInitializer {
  collected_for_day: DailyDepositAmountCollectedForDay;

  deposit_amount: string;
}

/** Represents the mutator for the table public.daily_deposit_amount */
export interface DailyDepositAmountMutator {
  collected_for_day?: DailyDepositAmountCollectedForDay;

  deposit_amount?: string;
}
