// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.deployed_contracts */
export type DeployedContractsDeployedByReceiptId = string & {
  __flavor?: "DeployedContractsDeployedByReceiptId";
};

/** Represents the table public.deployed_contracts */
export default interface DeployedContracts {
  deployed_by_receipt_id: DeployedContractsDeployedByReceiptId;

  contract_code_sha256: string;

  deployed_to_account_id: string;

  deployed_at_block_timestamp: string;

  deployed_at_block_hash: string;
}

/** Represents the initializer for the table public.deployed_contracts */
export interface DeployedContractsInitializer {
  deployed_by_receipt_id: DeployedContractsDeployedByReceiptId;

  contract_code_sha256: string;

  deployed_to_account_id: string;

  deployed_at_block_timestamp: string;

  /** Default value: ''::text */
  deployed_at_block_hash?: string;
}

/** Represents the mutator for the table public.deployed_contracts */
export interface DeployedContractsMutator {
  deployed_by_receipt_id?: DeployedContractsDeployedByReceiptId;

  contract_code_sha256?: string;

  deployed_to_account_id?: string;

  deployed_at_block_timestamp?: string;

  deployed_at_block_hash?: string;
}
