// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type {
  default as DailyAccountsAddedPerEcosystemEntity,
  DailyAccountsAddedPerEcosystemEntityInitializer,
  DailyAccountsAddedPerEcosystemEntityMutator,
} from "./daily-accounts-added-per-ecosystem-entity";
import type {
  default as DailyActiveAccountsCount,
  DailyActiveAccountsCountInitializer,
  DailyActiveAccountsCountMutator,
} from "./daily-active-accounts-count";
import type {
  default as DailyActiveContractsCount,
  DailyActiveContractsCountInitializer,
  DailyActiveContractsCountMutator,
} from "./daily-active-contracts-count";
import type {
  default as DailyDeletedAccountsCount,
  DailyDeletedAccountsCountInitializer,
  DailyDeletedAccountsCountMutator,
} from "./daily-deleted-accounts-count";
import type {
  default as DailyDepositAmount,
  DailyDepositAmountInitializer,
  DailyDepositAmountMutator,
} from "./daily-deposit-amount";
import type {
  default as DailyGasUsed,
  DailyGasUsedInitializer,
  DailyGasUsedMutator,
} from "./daily-gas-used";
import type {
  default as DailyIngoingTransactionsPerAccountCount,
  DailyIngoingTransactionsPerAccountCountInitializer,
  DailyIngoingTransactionsPerAccountCountMutator,
} from "./daily-ingoing-transactions-per-account-count";
import type {
  default as DailyNewAccountsCount,
  DailyNewAccountsCountInitializer,
  DailyNewAccountsCountMutator,
} from "./daily-new-accounts-count";
import type {
  default as DailyNewAccountsPerEcosystemEntityCount,
  DailyNewAccountsPerEcosystemEntityCountInitializer,
  DailyNewAccountsPerEcosystemEntityCountMutator,
} from "./daily-new-accounts-per-ecosystem-entity-count";
import type {
  default as DailyNewContractsCount,
  DailyNewContractsCountInitializer,
  DailyNewContractsCountMutator,
} from "./daily-new-contracts-count";
import type {
  default as DailyNewUniqueContractsCount,
  DailyNewUniqueContractsCountInitializer,
  DailyNewUniqueContractsCountMutator,
} from "./daily-new-unique-contracts-count";
import type {
  default as DailyOutgoingTransactionsPerAccountCount,
  DailyOutgoingTransactionsPerAccountCountInitializer,
  DailyOutgoingTransactionsPerAccountCountMutator,
} from "./daily-outgoing-transactions-per-account-count";
import type {
  default as DailyReceiptsPerContractCount,
  DailyReceiptsPerContractCountInitializer,
  DailyReceiptsPerContractCountMutator,
} from "./daily-receipts-per-contract-count";
import type {
  default as DailyTokensSpentOnFees,
  DailyTokensSpentOnFeesInitializer,
  DailyTokensSpentOnFeesMutator,
} from "./daily-tokens-spent-on-fees";
import type {
  default as DailyTransactionCountByGasBurntRanges,
  DailyTransactionCountByGasBurntRangesInitializer,
  DailyTransactionCountByGasBurntRangesMutator,
} from "./daily-transaction-count-by-gas-burnt-ranges";
import type {
  default as DailyTransactionsCount,
  DailyTransactionsCountInitializer,
  DailyTransactionsCountMutator,
} from "./daily-transactions-count";
import type {
  default as DeployedContracts,
  DeployedContractsInitializer,
  DeployedContractsMutator,
} from "./deployed-contracts";
import type {
  default as NearEcosystemEntities,
  NearEcosystemEntitiesInitializer,
  NearEcosystemEntitiesMutator,
} from "./near-ecosystem-entities";
import type {
  default as TransactionsWithConvertedReceipts,
  TransactionsWithConvertedReceiptsInitializer,
  TransactionsWithConvertedReceiptsMutator,
} from "./transactions-with-converted-receipts";
import type {
  default as UniqueContracts,
  UniqueContractsInitializer,
  UniqueContractsMutator,
} from "./unique-contracts";
import type {
  default as WeeklyActiveAccountsCount,
  WeeklyActiveAccountsCountInitializer,
  WeeklyActiveAccountsCountMutator,
} from "./weekly-active-accounts-count";

export type {
  default as DailyAccountsAddedPerEcosystemEntity,
  DailyAccountsAddedPerEcosystemEntityInitializer,
  DailyAccountsAddedPerEcosystemEntityMutator,
  DailyAccountsAddedPerEcosystemEntityEntityId,
  DailyAccountsAddedPerEcosystemEntityAccountId,
} from "./daily-accounts-added-per-ecosystem-entity";
export type {
  default as DailyActiveAccountsCount,
  DailyActiveAccountsCountInitializer,
  DailyActiveAccountsCountMutator,
  DailyActiveAccountsCountCollectedForDay,
} from "./daily-active-accounts-count";
export type {
  default as DailyActiveContractsCount,
  DailyActiveContractsCountInitializer,
  DailyActiveContractsCountMutator,
  DailyActiveContractsCountCollectedForDay,
} from "./daily-active-contracts-count";
export type {
  default as DailyDeletedAccountsCount,
  DailyDeletedAccountsCountInitializer,
  DailyDeletedAccountsCountMutator,
  DailyDeletedAccountsCountCollectedForDay,
} from "./daily-deleted-accounts-count";
export type {
  default as DailyDepositAmount,
  DailyDepositAmountInitializer,
  DailyDepositAmountMutator,
  DailyDepositAmountCollectedForDay,
} from "./daily-deposit-amount";
export type {
  default as DailyGasUsed,
  DailyGasUsedInitializer,
  DailyGasUsedMutator,
  DailyGasUsedCollectedForDay,
} from "./daily-gas-used";
export type {
  default as DailyIngoingTransactionsPerAccountCount,
  DailyIngoingTransactionsPerAccountCountInitializer,
  DailyIngoingTransactionsPerAccountCountMutator,
  DailyIngoingTransactionsPerAccountCountCollectedForDay,
  DailyIngoingTransactionsPerAccountCountAccountId,
} from "./daily-ingoing-transactions-per-account-count";
export type {
  default as DailyNewAccountsCount,
  DailyNewAccountsCountInitializer,
  DailyNewAccountsCountMutator,
  DailyNewAccountsCountCollectedForDay,
} from "./daily-new-accounts-count";
export type {
  default as DailyNewAccountsPerEcosystemEntityCount,
  DailyNewAccountsPerEcosystemEntityCountInitializer,
  DailyNewAccountsPerEcosystemEntityCountMutator,
  DailyNewAccountsPerEcosystemEntityCountCollectedForDay,
  DailyNewAccountsPerEcosystemEntityCountEntityId,
} from "./daily-new-accounts-per-ecosystem-entity-count";
export type {
  default as DailyNewContractsCount,
  DailyNewContractsCountInitializer,
  DailyNewContractsCountMutator,
  DailyNewContractsCountCollectedForDay,
} from "./daily-new-contracts-count";
export type {
  default as DailyNewUniqueContractsCount,
  DailyNewUniqueContractsCountInitializer,
  DailyNewUniqueContractsCountMutator,
  DailyNewUniqueContractsCountCollectedForDay,
} from "./daily-new-unique-contracts-count";
export type {
  default as DailyOutgoingTransactionsPerAccountCount,
  DailyOutgoingTransactionsPerAccountCountInitializer,
  DailyOutgoingTransactionsPerAccountCountMutator,
  DailyOutgoingTransactionsPerAccountCountCollectedForDay,
  DailyOutgoingTransactionsPerAccountCountAccountId,
} from "./daily-outgoing-transactions-per-account-count";
export type {
  default as DailyReceiptsPerContractCount,
  DailyReceiptsPerContractCountInitializer,
  DailyReceiptsPerContractCountMutator,
  DailyReceiptsPerContractCountCollectedForDay,
  DailyReceiptsPerContractCountContractId,
} from "./daily-receipts-per-contract-count";
export type {
  default as DailyTokensSpentOnFees,
  DailyTokensSpentOnFeesInitializer,
  DailyTokensSpentOnFeesMutator,
  DailyTokensSpentOnFeesCollectedForDay,
} from "./daily-tokens-spent-on-fees";
export type {
  default as DailyTransactionCountByGasBurntRanges,
  DailyTransactionCountByGasBurntRangesInitializer,
  DailyTransactionCountByGasBurntRangesMutator,
  DailyTransactionCountByGasBurntRangesCollectedForDay,
  DailyTransactionCountByGasBurntRangesTopOfRangeInTeragas,
} from "./daily-transaction-count-by-gas-burnt-ranges";
export type {
  default as DailyTransactionsCount,
  DailyTransactionsCountInitializer,
  DailyTransactionsCountMutator,
  DailyTransactionsCountCollectedForDay,
} from "./daily-transactions-count";
export type {
  default as DeployedContracts,
  DeployedContractsInitializer,
  DeployedContractsMutator,
  DeployedContractsDeployedByReceiptId,
} from "./deployed-contracts";
export type {
  default as NearEcosystemEntities,
  NearEcosystemEntitiesInitializer,
  NearEcosystemEntitiesMutator,
  NearEcosystemEntitiesSlug,
} from "./near-ecosystem-entities";
export type {
  default as TransactionsWithConvertedReceipts,
  TransactionsWithConvertedReceiptsInitializer,
  TransactionsWithConvertedReceiptsMutator,
  TransactionsWithConvertedReceiptsTransactionHash,
  TransactionsWithConvertedReceiptsReceiptId,
} from "./transactions-with-converted-receipts";
export type {
  default as UniqueContracts,
  UniqueContractsInitializer,
  UniqueContractsMutator,
  UniqueContractsContractCodeSha256,
} from "./unique-contracts";
export type {
  default as WeeklyActiveAccountsCount,
  WeeklyActiveAccountsCountInitializer,
  WeeklyActiveAccountsCountMutator,
  WeeklyActiveAccountsCountCollectedForWeek,
} from "./weekly-active-accounts-count";

export interface SelectorModelTypeMap {
  daily_accounts_added_per_ecosystem_entity: DailyAccountsAddedPerEcosystemEntity;

  daily_active_accounts_count: DailyActiveAccountsCount;

  daily_active_contracts_count: DailyActiveContractsCount;

  daily_deleted_accounts_count: DailyDeletedAccountsCount;

  daily_deposit_amount: DailyDepositAmount;

  daily_gas_used: DailyGasUsed;

  daily_ingoing_transactions_per_account_count: DailyIngoingTransactionsPerAccountCount;

  daily_new_accounts_count: DailyNewAccountsCount;

  daily_new_accounts_per_ecosystem_entity_count: DailyNewAccountsPerEcosystemEntityCount;

  daily_new_contracts_count: DailyNewContractsCount;

  daily_new_unique_contracts_count: DailyNewUniqueContractsCount;

  daily_outgoing_transactions_per_account_count: DailyOutgoingTransactionsPerAccountCount;

  daily_receipts_per_contract_count: DailyReceiptsPerContractCount;

  daily_tokens_spent_on_fees: DailyTokensSpentOnFees;

  daily_transaction_count_by_gas_burnt_ranges: DailyTransactionCountByGasBurntRanges;

  daily_transactions_count: DailyTransactionsCount;

  deployed_contracts: DeployedContracts;

  near_ecosystem_entities: NearEcosystemEntities;

  transactions_with_converted_receipts: TransactionsWithConvertedReceipts;

  unique_contracts: UniqueContracts;

  weekly_active_accounts_count: WeeklyActiveAccountsCount;
}

export interface InitializerModelTypeMap {
  daily_accounts_added_per_ecosystem_entity: DailyAccountsAddedPerEcosystemEntityInitializer;

  daily_active_accounts_count: DailyActiveAccountsCountInitializer;

  daily_active_contracts_count: DailyActiveContractsCountInitializer;

  daily_deleted_accounts_count: DailyDeletedAccountsCountInitializer;

  daily_deposit_amount: DailyDepositAmountInitializer;

  daily_gas_used: DailyGasUsedInitializer;

  daily_ingoing_transactions_per_account_count: DailyIngoingTransactionsPerAccountCountInitializer;

  daily_new_accounts_count: DailyNewAccountsCountInitializer;

  daily_new_accounts_per_ecosystem_entity_count: DailyNewAccountsPerEcosystemEntityCountInitializer;

  daily_new_contracts_count: DailyNewContractsCountInitializer;

  daily_new_unique_contracts_count: DailyNewUniqueContractsCountInitializer;

  daily_outgoing_transactions_per_account_count: DailyOutgoingTransactionsPerAccountCountInitializer;

  daily_receipts_per_contract_count: DailyReceiptsPerContractCountInitializer;

  daily_tokens_spent_on_fees: DailyTokensSpentOnFeesInitializer;

  daily_transaction_count_by_gas_burnt_ranges: DailyTransactionCountByGasBurntRangesInitializer;

  daily_transactions_count: DailyTransactionsCountInitializer;

  deployed_contracts: DeployedContractsInitializer;

  near_ecosystem_entities: NearEcosystemEntitiesInitializer;

  transactions_with_converted_receipts: TransactionsWithConvertedReceiptsInitializer;

  unique_contracts: UniqueContractsInitializer;

  weekly_active_accounts_count: WeeklyActiveAccountsCountInitializer;
}

export interface MutatorModelTypeMap {
  daily_accounts_added_per_ecosystem_entity: DailyAccountsAddedPerEcosystemEntityMutator;

  daily_active_accounts_count: DailyActiveAccountsCountMutator;

  daily_active_contracts_count: DailyActiveContractsCountMutator;

  daily_deleted_accounts_count: DailyDeletedAccountsCountMutator;

  daily_deposit_amount: DailyDepositAmountMutator;

  daily_gas_used: DailyGasUsedMutator;

  daily_ingoing_transactions_per_account_count: DailyIngoingTransactionsPerAccountCountMutator;

  daily_new_accounts_count: DailyNewAccountsCountMutator;

  daily_new_accounts_per_ecosystem_entity_count: DailyNewAccountsPerEcosystemEntityCountMutator;

  daily_new_contracts_count: DailyNewContractsCountMutator;

  daily_new_unique_contracts_count: DailyNewUniqueContractsCountMutator;

  daily_outgoing_transactions_per_account_count: DailyOutgoingTransactionsPerAccountCountMutator;

  daily_receipts_per_contract_count: DailyReceiptsPerContractCountMutator;

  daily_tokens_spent_on_fees: DailyTokensSpentOnFeesMutator;

  daily_transaction_count_by_gas_burnt_ranges: DailyTransactionCountByGasBurntRangesMutator;

  daily_transactions_count: DailyTransactionsCountMutator;

  deployed_contracts: DeployedContractsMutator;

  near_ecosystem_entities: NearEcosystemEntitiesMutator;

  transactions_with_converted_receipts: TransactionsWithConvertedReceiptsMutator;

  unique_contracts: UniqueContractsMutator;

  weekly_active_accounts_count: WeeklyActiveAccountsCountMutator;
}
