// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.near_ecosystem_entities */
export type NearEcosystemEntitiesSlug = string & {
  __flavor?: "NearEcosystemEntitiesSlug";
};

/** Represents the table public.near_ecosystem_entities */
export default interface NearEcosystemEntities {
  slug: NearEcosystemEntitiesSlug;

  title: string | null;

  oneliner: string | null;

  website: string | null;

  category: string | null;

  status: string | null;

  contract: string | null;

  logo: string | null;

  is_app: boolean | null;

  is_nft: boolean | null;

  is_guild: boolean | null;

  is_defi: boolean | null;

  is_dao: boolean | null;
}

/** Represents the initializer for the table public.near_ecosystem_entities */
export interface NearEcosystemEntitiesInitializer {
  slug: NearEcosystemEntitiesSlug;

  title?: string | null;

  oneliner?: string | null;

  website?: string | null;

  category?: string | null;

  status?: string | null;

  contract?: string | null;

  logo?: string | null;

  is_app?: boolean | null;

  is_nft?: boolean | null;

  is_guild?: boolean | null;

  is_defi?: boolean | null;

  is_dao?: boolean | null;
}

/** Represents the mutator for the table public.near_ecosystem_entities */
export interface NearEcosystemEntitiesMutator {
  slug?: NearEcosystemEntitiesSlug;

  title?: string | null;

  oneliner?: string | null;

  website?: string | null;

  category?: string | null;

  status?: string | null;

  contract?: string | null;

  logo?: string | null;

  is_app?: boolean | null;

  is_nft?: boolean | null;

  is_guild?: boolean | null;

  is_defi?: boolean | null;

  is_dao?: boolean | null;
}
