// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.transactions_with_converted_receipts */
export type TransactionsWithConvertedReceiptsTransactionHash = string & {
  __flavor?: "TransactionsWithConvertedReceiptsTransactionHash";
};

/** Identifier type for public.transactions_with_converted_receipts */
export type TransactionsWithConvertedReceiptsReceiptId = string & {
  __flavor?: "TransactionsWithConvertedReceiptsReceiptId";
};

/** Represents the table public.transactions_with_converted_receipts */
export default interface TransactionsWithConvertedReceipts {
  transaction_hash: TransactionsWithConvertedReceiptsTransactionHash;

  receipt_id: TransactionsWithConvertedReceiptsReceiptId;
}

/** Represents the initializer for the table public.transactions_with_converted_receipts */
export interface TransactionsWithConvertedReceiptsInitializer {
  transaction_hash: TransactionsWithConvertedReceiptsTransactionHash;

  receipt_id: TransactionsWithConvertedReceiptsReceiptId;
}

/** Represents the mutator for the table public.transactions_with_converted_receipts */
export interface TransactionsWithConvertedReceiptsMutator {
  transaction_hash?: TransactionsWithConvertedReceiptsTransactionHash;

  receipt_id?: TransactionsWithConvertedReceiptsReceiptId;
}
