// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.unique_contracts */
export type UniqueContractsContractCodeSha256 = string & {
  __flavor?: "UniqueContractsContractCodeSha256";
};

/** Represents the table public.unique_contracts */
export default interface UniqueContracts {
  contract_code_sha256: UniqueContractsContractCodeSha256;

  contract_sdk_type: string;

  first_deployed_to_account_id: string;

  first_deployed_by_receipt_id: string;

  first_deployed_at_block_timestamp: string;

  first_deployed_at_block_hash: string;
}

/** Represents the initializer for the table public.unique_contracts */
export interface UniqueContractsInitializer {
  contract_code_sha256: UniqueContractsContractCodeSha256;

  /** Default value: ''::text */
  contract_sdk_type?: string;

  first_deployed_to_account_id: string;

  first_deployed_by_receipt_id: string;

  first_deployed_at_block_timestamp: string;

  first_deployed_at_block_hash: string;
}

/** Represents the mutator for the table public.unique_contracts */
export interface UniqueContractsMutator {
  contract_code_sha256?: UniqueContractsContractCodeSha256;

  contract_sdk_type?: string;

  first_deployed_to_account_id?: string;

  first_deployed_by_receipt_id?: string;

  first_deployed_at_block_timestamp?: string;

  first_deployed_at_block_hash?: string;
}
