// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.weekly_active_accounts_count */
export type WeeklyActiveAccountsCountCollectedForWeek = Date & {
  __flavor?: "WeeklyActiveAccountsCountCollectedForWeek";
};

/** Represents the table public.weekly_active_accounts_count */
export default interface WeeklyActiveAccountsCount {
  collected_for_week: WeeklyActiveAccountsCountCollectedForWeek;

  active_accounts_count: number;
}

/** Represents the initializer for the table public.weekly_active_accounts_count */
export interface WeeklyActiveAccountsCountInitializer {
  collected_for_week: WeeklyActiveAccountsCountCollectedForWeek;

  active_accounts_count: number;
}

/** Represents the mutator for the table public.weekly_active_accounts_count */
export interface WeeklyActiveAccountsCountMutator {
  collected_for_week?: WeeklyActiveAccountsCountCollectedForWeek;

  active_accounts_count?: number;
}
