// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { default as Nodes, NodesInitializer, NodesMutator } from "./nodes";

export type {
  default as Nodes,
  NodesInitializer,
  NodesMutator,
  NodesNodeId,
} from "./nodes";

export interface SelectorModelTypeMap {
  nodes: Nodes;
}

export interface InitializerModelTypeMap {
  nodes: NodesInitializer;
}

export interface MutatorModelTypeMap {
  nodes: NodesMutator;
}
