// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.nodes */
export type NodesNodeId = string & { __flavor?: "NodesNodeId" };

/** Represents the table public.nodes */
export default interface Nodes {
  node_id: NodesNodeId;

  ip_address: string;

  moniker: string;

  account_id: string;

  last_seen: Date;

  last_height: string;

  agent_name: string;

  agent_version: string;

  agent_build: string;

  peer_count: string;

  is_validator: boolean;

  last_hash: string;

  signature: string;

  status: string;

  latitude: string | null;

  longitude: string | null;

  city: string | null;

  bandwidth_download: number | null;

  bandwidth_upload: number | null;

  cpu_usage: number | null;

  memory_usage: string | null;

  boot_time_seconds: Date | null;

  block_production_tracking_delay: number | null;

  min_block_production_delay: number | null;

  max_block_production_delay: number | null;

  max_block_wait_delay: number | null;
}

/** Represents the initializer for the table public.nodes */
export interface NodesInitializer {
  node_id: NodesNodeId;

  ip_address: string;

  moniker: string;

  account_id: string;

  last_seen: Date;

  last_height: string;

  agent_name: string;

  agent_version: string;

  agent_build: string;

  peer_count: string;

  is_validator: boolean;

  last_hash: string;

  signature: string;

  status: string;

  latitude?: string | null;

  longitude?: string | null;

  city?: string | null;

  bandwidth_download?: number | null;

  bandwidth_upload?: number | null;

  cpu_usage?: number | null;

  memory_usage?: string | null;

  boot_time_seconds?: Date | null;

  block_production_tracking_delay?: number | null;

  min_block_production_delay?: number | null;

  max_block_production_delay?: number | null;

  max_block_wait_delay?: number | null;
}

/** Represents the mutator for the table public.nodes */
export interface NodesMutator {
  node_id?: NodesNodeId;

  ip_address?: string;

  moniker?: string;

  account_id?: string;

  last_seen?: Date;

  last_height?: string;

  agent_name?: string;

  agent_version?: string;

  agent_build?: string;

  peer_count?: string;

  is_validator?: boolean;

  last_hash?: string;

  signature?: string;

  status?: string;

  latitude?: string | null;

  longitude?: string | null;

  city?: string | null;

  bandwidth_download?: number | null;

  bandwidth_upload?: number | null;

  cpu_usage?: number | null;

  memory_usage?: string | null;

  boot_time_seconds?: Date | null;

  block_production_tracking_delay?: number | null;

  min_block_production_delay?: number | null;

  max_block_production_delay?: number | null;

  max_block_wait_delay?: number | null;
}
