name: Delete GCP Explorer Environments of closed PR

# only trigger on pull request closed events
on:
  pull_request:
    types: [closed]

jobs:
  merge_job:
    runs-on: ubuntu-latest
    steps:
      - name: "Authenticate to GCloud"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.CI_EXPLORER_FRONTEND_SA_STAGING_KEY }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - name: "Remove Frontend dev environment for closed PR"
        run: |
          gcloud run services update-traffic "explorer-frontend" --remove_tags "$PR_NUMBER"
        env:
          PR_NUMBER: ${{ github.event.number }}

      - name: "Remove Backend Testnet dev environment for closed PR"
        run: |
          gcloud run services update-traffic "explorer-backend-testnet" --remove_tags "$PR_NUMBER"
        env:
          PR_NUMBER: ${{ github.event.number }}

      - name: "Remove Backend Mainnet dev environment for closed PR"
        run: |
          gcloud run services update-traffic "explorer-frontend-mainnet" --remove_tags "$PR_NUMBER"
        env:
          PR_NUMBER: ${{ github.event.number }}
