name: Deploy to Staging environment.
on:
  pull_request:
    branches:
      - master

env:
  BACKEND_IMAGE: "us-central1-docker.pkg.dev/pagoda-data-stack-dev/cloud-run-source-deploy/explorer-backend"
  FRONTEND_IMAGE: "us-central1-docker.pkg.dev/pagoda-data-stack-dev/cloud-run-source-deploy/explorer-frontend"
  PR_NUMBER: ${{ github.event.number }}
  REGION: "us-central1"

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: "Checkout near-explorer"

      - name: "Authenticate to GCloud"
        uses: "google-github-actions/auth@v1"
        id: "auth"
        with:
          credentials_json: "${{ secrets.CI_EXPLORER_FRONTEND_SA_STAGING_KEY }}"

      - name: Login to Artifact Registry
        uses: docker/login-action@v2
        with:
          registry: us-central1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.CI_EXPLORER_FRONTEND_SA_STAGING_KEY }}

      - id: docker-push-tagged
        name: Tag Docker image and push to Google Artifact Registry
        uses: docker/build-push-action@v4
        with:
          push: true
          file: ./frontend/Dockerfile
          tags: "${{ env.FRONTEND_IMAGE }}:${{ env.PR_NUMBER }}"

  # deploy-frontend:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #       name: "Checkout near-explorer"

  #     - name: "Authenticate to GCloud"
  #       uses: "google-github-actions/auth@v1"
  #       with:
  #         credentials_json: "${{ secrets.CI_EXPLORER_FRONTEND_SA_STAGING_KEY }}"

  #     - name: "Build the Frontend"
  #       run: |
  #         docker build -f "frontend/Dockerfile" -t "${_IMAGE}:${_PR_NUMBER}" "."

  #     - name: "Configure docker with gcloud"
  #       run: |
  #         gcloud auth configure-docker -q

  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: "Checkout backend-repo"

      - name: "Authenticate to GCloud"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.CI_EXPLORER_FRONTEND_SA_STAGING_KEY }}"

      - name: "Build the Backend"
        run: |
          gcloud builds submit "." --config=".github/gcp-configs/gcp-backend-build.yaml" --gcs-log-dir="gs://near-explorer-frontend-ci-logs/explorer-ci"\
           --machine-type="e2-highcpu-8" --substitutions="_PR_NUMBER=$PR_NUMBER,_IMAGE=$BACKEND_IMAGE"
        env:
          PR_NUMBER: ${{ github.event.number }}

  deploy-backend-testnet:
    environment:
      name: dev-backend-testnet
      url: ${{ steps.gcp_url.outputs.deploy_url }}
    runs-on: ubuntu-latest
    needs: build-backend
    steps:
      - uses: actions/checkout@v3
        name: "Checkout backend-repo"

      - name: "Authenticate to GCloud"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.CI_EXPLORER_FRONTEND_SA_STAGING_KEY }}"

      - name: "Deploy Backend Testnet"
        run: |
          gcloud builds submit "." --config=".github/gcp-configs/gcp-backend-deploy.yaml" --gcs-log-dir="gs://near-explorer-frontend-ci-logs/explorer-ci"\
           --machine-type="e2-highcpu-8" --substitutions="_CLOUD_RUN_SERVICE=explorer-backend-testnet,_IMAGE=$BACKEND_IMAGE,_PR_NUMBER=$PR_NUMBER,_REGION=$REGION"
        env:
          PR_NUMBER: ${{ github.event.number }}

      - name: "Get deployment URL"
        id: "gcp_url"
        run: |
          url=$(gcloud run services describe "explorer-backend-testnet" --platform managed --region "${REGION}" --project "pagoda-data-stack-dev"\
           --format 'value(status.url)')
          match="https://"
          tagged_url="https://${url%%${match}*}pr-${PR_NUMBER}---${url##*${match}}"
          echo deploy_url=$tagged_url >> $GITHUB_OUTPUT
        env:
          PR_NUMBER: ${{ github.event.number }}

  deploy-backend-mainnet:
    environment:
      name: dev-backend-mainnet
      url: ${{ steps.gcp_url.outputs.deploy_url }}
    runs-on: ubuntu-latest
    needs: build-backend
    steps:
      - uses: actions/checkout@v3
        name: "Checkout backend-repo"

      - name: "Authenticate to GCloud"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.CI_EXPLORER_FRONTEND_SA_STAGING_KEY }}"

      - name: "Deploy Backend Mainnet"
        run: |
          gcloud builds submit "." --config=".github/gcp-configs/gcp-backend-deploy.yaml" --gcs-log-dir="gs://near-explorer-frontend-ci-logs/explorer-ci"\
          --machine-type="e2-highcpu-8" --substitutions="_CLOUD_RUN_SERVICE=explorer-backend-mainnet,_PR_NUMBER=$PR_NUMBER,_REGION=$REGION,_IMAGE=$BACKEND_IMAGE"
        env:
          PR_NUMBER: ${{ github.event.number }}

      - name: "Get deployment URL"
        id: "gcp_url"
        run: |
          url=$(gcloud run services describe "explorer-backend-mainnet" --platform managed --region "${REGION}" --project "pagoda-data-stack-dev"\
           --format 'value(status.url)')
          match="https://"
          tagged_url="https://${url%%${match}*}pr-${PR_NUMBER}---${url##*${match}}"
          echo deploy_url=$tagged_url >> $GITHUB_OUTPUT
        env:
          PR_NUMBER: ${{ github.event.number }}
