name: Deploy to Staging environment.
on:
  pull_request:
    branches:
      - master

env:
  REGION: "us-central1"
  BACKEND_IMAGE: "us-central1-docker.pkg.dev/pagoda-data-stack-dev/cloud-run-source-deploy/explorer-backend"
  FRONTEND_IMAGE: "us-central1-docker.pkg.dev/pagoda-data-stack-dev/cloud-run-source-deploy/explorer-frontend"
  PR_NUMBER: ${{ github.event.number }}

jobs:
  env-setup:
    runs-on: ubuntu-latest
    steps:
      - name: "Generate outputs to be used as input in reusable workflows"
        id: env-setup
        run: |
          echo "REGION=${{ env.REGION }}" >> $GITHUB_OUTPUT
          echo "BACKEND_IMAGE=${{ env.BACKEND_IMAGE }}" >> $GITHUB_OUTPUT
          echo "FRONTEND_IMAGE=${{ env.FRONTEND_IMAGE }}" >> $GITHUB_OUTPUT
          echo "PR_NUMBER=${{ env.PR_NUMBER }}" >> $GITHUB_OUTPUT
    outputs:
      REGION: ${{ steps['env-setup'].outputs.REGION }}
      BACKEND_IMAGE: ${{ steps['env-setup'].outputs.BACKEND_IMAGE }}
      FRONTEND_IMAGE: ${{ steps['env-setup'].outputs.FRONTEND_IMAGE }}
      PR_NUMBER: ${{ steps['env-setup'].outputs.PR_NUMBER }}

  build-frontend:
    uses: ./.github/workflows/gcp-build.yml
    needs: env-setup
    with:
      dockerfile_path: "./frontend/Dockerfile"
      image_path: "${{ needs.env-setup.outputs.FRONTEND_IMAGE }}"
      region: "${{ needs.env-setup.outputs.REGION }}"
      pr_number: "${{ github.event.number }}"
    secrets:
      service_account_key: ${{ secrets.CI_EXPLORER_UI_SA_DEV_KEY }}

  get-backend-service-urls:
    needs: build-frontend
    runs-on: ubuntu-latest
    outputs:
      backend_testnet_url: ${{ steps.get_urls.outputs.BACKEND_TESTNET_URL }}
      backend_mainnet_url: ${{ steps.get_urls.outputs.BACKEND_MAINNET_URL }}
    steps:
      - name: "Authenticate to GCloud"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.CI_EXPLORER_UI_SA_DEV_KEY }}"

      - name: "Get Backend services URLs"
        id: get_urls
        run: |
          backend_testnet_url=$(gcloud run services describe "explorer-backend-testnet" --platform managed --region "${{ env.REGION }}" --project "pagoda-data-stack-dev"\
           --format='value(status.url)')
          backend_mainnet_url=$(gcloud run services describe "explorer-backend-mainnet" --platform managed --region "${{ env.REGION }}" --project "pagoda-data-stack-dev"\
           --format='value(status.url)')
          prefix="https://"
          backend_testnet_url="${backend_testnet_url#"$prefix"}"
          backend_mainnet_url="${backend_mainnet_url#"$prefix"}"
          echo "BACKEND_TESTNET_URL=${backend_testnet_url}" >> $GITHUB_OUTPUT
          echo "BACKEND_MAINNET_URL=${backend_mainnet_url}" >> $GITHUB_OUTPUT

  deploy-frontend:
    uses: ./.github/workflows/gcp-deploy.yml
    needs:
      - get-backend-service-urls
      - env-setup
    with:
      environment_name: "dev-frontend"
      cloud_run_service_name: "explorer-frontend"
      deploy_tag: "pr-${{ github.event.number }}"
      docker_image: "${{ needs.env-setup.outputs.FRONTEND_IMAGE }}"
      gcp_project_id: "pagoda-data-stack-dev"
      region: "${{ needs.env-setup.outputs.REGION }}"
      env_vars: >-
        {
          \"GCP\": \"true\",
          \"COMMIT_SHA\": \"$GITHUB_SHA\",
          \"BRANCH\": \"$GITHUB_REF_NAME\",
          \"NEAR_EXPLORER_CONFIG__BACKEND_SSR__HOSTS__MAINNET\": \"pr-${{ github.event.number }}---${{ needs.get-backend-service-urls.outputs.backend_mainnet_url }}\",
          \"NEAR_EXPLORER_CONFIG__BACKEND_SSR__HOSTS__TESTNET\": \"pr-${{ github.event.number }}---${{ needs.get-backend-service-urls.outputs.backend_testnet_url }}\",
          \"NEAR_EXPLORER_CONFIG__BACKEND__HOSTS__MAINNET\": \"pr-${{ github.event.number }}---${{ needs.get-backend-service-urls.outputs.backend_mainnet_url }}\",
          \"NEAR_EXPLORER_CONFIG__BACKEND__HOSTS__TESTNET\": \"pr-${{ github.event.number }}---${{ needs.get-backend-service-urls.outputs.backend_testnet_url }}\"
        }
    secrets:
      service_account_key: ${{ secrets.CI_EXPLORER_UI_SA_DEV_KEY }}

  build-backend:
    uses: ./.github/workflows/gcp-build.yml
    needs: env-setup
    with:
      dockerfile_path: "./backend/Dockerfile"
      image_path: "${{ needs.env-setup.outputs.BACKEND_IMAGE }}"
      region: "${{ needs.env-setup.outputs.REGION }}"
      pr_number: "${{ github.event.number }}"
    secrets:
      service_account_key: ${{ secrets.CI_EXPLORER_UI_SA_DEV_KEY }}

  deploy-backend-testnet:
    uses: ./.github/workflows/gcp-deploy.yml
    needs:
      - build-backend
      - env-setup
    with:
      environment_name: "dev-backend-testnet"
      cloud_run_service_name: "explorer-backend-testnet"
      deploy_tag: "pr-${{ github.event.number }}"
      docker_image: "${{ needs.env-setup.outputs.BACKEND_IMAGE }}"
      gcp_project_id: "pagoda-data-stack-dev"
      region: "${{ needs.env-setup.outputs.REGION }}"
      env_vars: >-
        {
          \"COMMIT_SHA\": \"$GITHUB_SHA\",
          \"BRANCH\": \"$GITHUB_REF_NAME\"
        }
    secrets:
      service_account_key: ${{ secrets.CI_EXPLORER_UI_SA_DEV_KEY }}

  deploy-backend-mainnet:
    uses: ./.github/workflows/gcp-deploy.yml
    needs:
      - build-backend
      - env-setup
    with:
      environment_name: "dev-backend-mainnet"
      cloud_run_service_name: "explorer-backend-mainnet"
      deploy_tag: "pr-${{ github.event.number }}"
      docker_image: "${{ needs.env-setup.outputs.BACKEND_IMAGE }}"
      gcp_project_id: "pagoda-data-stack-dev"
      region: "${{ needs.env-setup.outputs.REGION }}"
      env_vars: >-
        {
          \"COMMIT_SHA\": \"$GITHUB_SHA\",
          \"BRANCH\": \"$GITHUB_REF_NAME\"
        }
    secrets:
      service_account_key: ${{ secrets.CI_EXPLORER_UI_SA_DEV_KEY }}
